[project]
name = "aibetter-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.116.1",
    "pre-commit>=4.2.0",
    "requests>=2.32.4",
    "slowapi>=0.1.9",
    "uvicorn>=0.35.0",
]
